"""Shared application data models."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

SEMANTIC_ROLES: tuple[str, ...] = (
    "index",
    "profit",
    "capacity",
    "demand",
    "cost",
    "lower_bound",
    "upper_bound",
)


@dataclass(slots=True)
class ImportJob:
    """One queued import request from the GUI."""

    table_name: str
    selected_columns: list[str]
    max_rows: int
    symbol_name: str
    where_clause: str = ""
    semantic_roles: dict[str, str] = field(default_factory=dict)
    structured_index_columns: list[str] = field(default_factory=list)
    structured_value_columns: list[str] = field(default_factory=list)


@dataclass(slots=True)
class MaterializedImportJob:
    """An import job with fetched preview/export data attached."""

    job: ImportJob
    dataframe: pd.DataFrame


@dataclass(slots=True)
class ExportArtifacts:
    """Files generated by the multi-import export pipeline."""

    preview_csv: Path
    legacy_long_csv: Path
    job_directory: Path
    manifest_csv: Path
    reconciliation_catalog_csv: Path
    semantic_coordination_csv: Path
    generated_runtime_include: Path
    generated_symbol_include: Path
    generated_modeling_helper_include: Path
    generated_reconciliation_helper_include: Path
    generated_example_model: Path
    generated_multi_job_example_model: Path
    generated_reconciliation_example_model: Path
    generated_unload_include: Path
    generated_semantic_declarations_include: Path
    generated_semantic_mapping_include: Path
    generated_structured_declarations_include: Path
    generated_structured_assignments_include: Path
    symbol_catalog_csv: Path
    symbol_names: list[str]
    primary_symbol_name: str
